### ISSUE TITLE
IMP/BUG: preserve .github directory

### ISSUE THREAD

**Issue by thermokarst** [qiime2/template-repo#16]
I recently had this templater run on qiime2/library, and it wiped out all of my github workflows (I assumed because it blindly overwrites the entire `.github` directory.

**Comment by thermokarst** [comment]
@Oddant1 - interested? If so, please assign to yourself. Let me know what kind of detail you need - the issue above is a bit anemic.

**Comment by Oddant1** [comment]
@thermokarst trying to make sure I know what exactly is going on here. The code here templates out the .github folders in repos (among other things perhaps?) and you want it to add what it templates to the existing .github repo instead of replacing the existing .github repo? That's my initial impressions of what this issue is anyway, let me know how far off I am.

**Comment by Oddant1** [comment]
This code block here, particularly line 32, seems to be the culprit

https://github.com/qiime2/template-repo/blob/c4ec1e54d3dca845c4d91799170011fef167832d/github_templates/update_templates.sh#L29-L33
